documentation:
  image: sparkfabrik/docker-locke-server:latest
  environment:
    - DNSDOCK_ALIAS=playbook.sparkfabrik.loc
  volumes:
    - ./assets:/srv/locke/assets
    - ./content:/srv/locke/content
    - ./config.js:/srv/locke/config.js